# Generated by Django 3.2.7 on 2021-09-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_user_id', models.BigIntegerField()),
                ('email_id', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=256, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=256, null=True)),
                ('last_login_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user_since_timestamp', models.DateTimeField(blank=True, null=True)),
                ('profile_update_timestamp', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('f_name', models.CharField(blank=True, max_length=256, null=True)),
                ('m_name', models.CharField(blank=True, max_length=256, null=True)),
                ('l_name', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_street1', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_street2', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_post_office', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_city', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_district', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_state', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_zipcode', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_street1', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_street2', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_street3', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_post_office', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_zipcode', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=256, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(blank=True, max_length=256, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=256, null=True)),
                ('degree_type', models.CharField(blank=True, max_length=256, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=256, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=256, null=True)),
                ('month_of_joining', models.CharField(blank=True, max_length=256, null=True)),
                ('year_of_joining', models.CharField(blank=True, max_length=256, null=True)),
                ('month_of_graduation', models.CharField(blank=True, max_length=256, null=True)),
                ('year_of_graduation', models.CharField(blank=True, max_length=256, null=True)),
                ('college_orginal_name', models.CharField(blank=True, max_length=256, null=True)),
                ('college_pincode', models.CharField(blank=True, max_length=256, null=True)),
                ('calculated_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('complete_approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fk_college_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
    ]
