
from django.db import models


class TblUsers(models.Model):
    id = models.BigAutoField(primary_key=True)
    fk_user_id = models.BigIntegerField()
    email_id = models.CharField(max_length=256, blank=True, null=True)
    mobile_no = models.CharField(max_length=256, blank=True, null=True)
    ip_address = models.CharField(max_length=256, blank=True, null=True)
    mac_address = models.CharField(max_length=256, blank=True, null=True)
    last_login_timestamp = models.DateTimeField(blank=True, null=True)
    user_since_timestamp = models.DateTimeField(blank=True, null=True)
    profile_update_timestamp = models.DateTimeField(blank=True, null=True)
    display_name = models.CharField(max_length=256, blank=True, null=True)
    f_name = models.CharField(max_length=256, blank=True, null=True)
    m_name = models.CharField(max_length=256, blank=True, null=True)
    l_name = models.CharField(max_length=256, blank=True, null=True)
    residence_street1 = models.CharField(max_length=256, blank=True, null=True)
    residence_street2 = models.CharField(max_length=256, blank=True, null=True)
    residence_post_office = models.CharField(max_length=256, blank=True, null=True)
    residence_city = models.CharField(max_length=256, blank=True, null=True)
    residence_district = models.CharField(max_length=256, blank=True, null=True)
    residence_state = models.CharField(max_length=256, blank=True, null=True)
    residence_zipcode = models.CharField(max_length=256, blank=True, null=True)
    residence_phone = models.CharField(max_length=256, blank=True, null=True)
    permanent_street1 = models.CharField(max_length=256, blank=True, null=True)
    permanent_street2 = models.CharField(max_length=256, blank=True, null=True)
    permanent_street3 = models.CharField(max_length=256, blank=True, null=True)
    permanent_post_office = models.CharField(max_length=256, blank=True, null=True)
    permanent_city = models.CharField(max_length=256, blank=True, null=True)
    permanent_district = models.CharField(max_length=256, blank=True, null=True)
    permanent_state = models.CharField(max_length=256, blank=True, null=True)
    permanent_zipcode = models.CharField(max_length=256, blank=True, null=True)
    permanent_phone = models.CharField(max_length=256, blank=True, null=True)
    date_of_birth = models.CharField(max_length=256, blank=True, null=True)
    fathers_name = models.CharField(max_length=256, blank=True, null=True)
    mothers_name = models.CharField(max_length=256, blank=True, null=True)
    gender = models.CharField(max_length=256, blank=True, null=True)
    marital_status = models.CharField(max_length=256, blank=True, null=True)
    degree_type = models.CharField(max_length=256, blank=True, null=True)
    degree_name = models.CharField(max_length=256, blank=True, null=True)
    field_of_study = models.CharField(max_length=256, blank=True, null=True)
    month_of_joining = models.CharField(max_length=256, blank=True, null=True)
    year_of_joining = models.CharField(max_length=256, blank=True, null=True)
    month_of_graduation = models.CharField(max_length=256, blank=True, null=True)
    year_of_graduation = models.CharField(max_length=256, blank=True, null=True)
    college_orginal_name = models.CharField(max_length=256, blank=True, null=True)
    college_pincode = models.CharField(max_length=256, blank=True, null=True)
    calculated_credit_limit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    adjusted_credit_limit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    total_credit_limit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    available_credit_limit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    complete_approval_timestamp = models.DateTimeField(blank=True, null=True)
    fk_college_id = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tbl_users'